
## Import Libaries

In [90]:
from statistics import linear_regression
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, confusion_matrix



## Load Dataset and extract dependent and independent variables

In [91]:
# Load Dataset
reading_data = "C:/Users/ADMIN/Desktop/Datasets/diabetes.csv"
data = pd.read_csv(reading_data)
data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

## Create Train and Test Data

In [92]:
# Creating training and testing data
X = data.iloc[:, :8].values
y = data.iloc[:, -3].values

In [93]:
# Splitting the dataset into the Training set and Test Set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=100)
X_train

array([[  7.   , 152.   ,  88.   , ...,  50.   ,   0.337,  36.   ],
       [  1.   , 136.   ,  74.   , ...,  37.4  ,   0.399,  24.   ],
       [  0.   , 131.   ,   0.   , ...,  43.2  ,   0.27 ,  26.   ],
       ...,
       [  4.   ,  92.   ,  80.   , ...,  42.2  ,   0.237,  29.   ],
       [  2.   , 112.   ,  66.   , ...,  25.   ,   0.307,  24.   ],
       [  2.   ,  68.   ,  70.   , ...,  25.   ,   0.187,  25.   ]])

In [94]:
# Fitting Multiple Linear Regression  to the Training set
regressor = LinearRegression(fit_intercept = True, copy_X = True, n_jobs = 2)
regressor.fit(X_train, y_train)

LinearRegression(n_jobs=2)

In [95]:
# Predicting the Test Set Results
y_pred = regressor.predict(X_test)
y_pred[:10]


array([0.678, 0.238, 0.151, 0.6  , 0.374, 0.443, 0.817, 0.51 , 0.875,
       0.466])

In [96]:
y_test[:10]

array([0.678, 0.238, 0.151, 0.6  , 0.374, 0.443, 0.817, 0.51 , 0.875,
       0.466])

In [97]:
# Calculating the co-efficients
print(regressor.coef_)

[-9.17722860e-18  1.82145965e-17  3.80554963e-17  6.87519703e-17
 -2.16840434e-19 -3.97722626e-16  1.00000000e+00 -7.26415456e-18]


In [98]:
#Calculating the intercept
print(regressor.intercept_)

6.439293542825908e-15


## Model Accuracy

In [99]:
# Calculating the R Squared value
r2_score(y_test, y_pred)*100


100.0